spring:
  
  datasource:
    url: jdbc:mysql://localhost:3306/tiktok01
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  redis:
    host: ${REDIS_HOST:172.17.50.84}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:123456}
    
  mail:
    host: smtp.qq.com
    port: 465
    username: ${MAIL_NAME:2378150995@qq.com}
    password: ${MAIL_PASSWORD:bpqezbkddzogdjff}
    properties:
      mail:
        smtp:
          ssl:
            enable: true

server:
  port: 8888